//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTaskPriority", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    public enum DTaskPriority : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTask", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    public partial class DTask : object
    {
        
        private string ErrorMessageField;
        
        private string FileNameField;
        
        private ServiceReference1.DTaskPriority PriorityField;
        
        private double ProgressField;
        
        private ServiceReference1.DTaskStatus StatusField;
        
        private string TargetPathField;
        
        private string TaskIdField;
        
        private string UrlField;
        
        private string timeLeftTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.DTaskPriority Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Progress
        {
            get
            {
                return this.ProgressField;
            }
            set
            {
                this.ProgressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.DTaskStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetPath
        {
            get
            {
                return this.TargetPathField;
            }
            set
            {
                this.TargetPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskId
        {
            get
            {
                return this.TaskIdField;
            }
            set
            {
                this.TaskIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string timeLeftText
        {
            get
            {
                return this.timeLeftTextField;
            }
            set
            {
                this.timeLeftTextField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTaskStatus", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    public enum DTaskStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Queued = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paused = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Downloading = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finished = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EnqueueDownload", ReplyAction="http://tempuri.org/IService1/EnqueueDownloadResponse")]
        System.Threading.Tasks.Task<ServiceReference1.EnqueueDownloadResponse> EnqueueDownloadAsync(ServiceReference1.EnqueueDownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDownloadQueue", ReplyAction="http://tempuri.org/IService1/GetDownloadQueueResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetDownloadQueueResponse> GetDownloadQueueAsync(ServiceReference1.GetDownloadQueueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StartDownloadOne", ReplyAction="http://tempuri.org/IService1/StartDownloadOneResponse")]
        System.Threading.Tasks.Task<ServiceReference1.StartDownloadOneResponse> StartDownloadOneAsync(ServiceReference1.StartDownloadOneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDownloadedList", ReplyAction="http://tempuri.org/IService1/GetDownloadedListResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetDownloadedListResponse> GetDownloadedListAsync(ServiceReference1.GetDownloadedListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PauseDownload", ReplyAction="http://tempuri.org/IService1/PauseDownloadResponse")]
        System.Threading.Tasks.Task<ServiceReference1.PauseDownloadResponse> PauseDownloadAsync(ServiceReference1.PauseDownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ResumeDownload", ReplyAction="http://tempuri.org/IService1/ResumeDownloadResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResumeDownloadResponse> ResumeDownloadAsync(ServiceReference1.ResumeDownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CancelDownload", ReplyAction="http://tempuri.org/IService1/CancelDownloadResponse")]
        System.Threading.Tasks.Task<ServiceReference1.CancelDownloadResponse> CancelDownloadAsync(ServiceReference1.CancelDownloadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnqueueDownload", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EnqueueDownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string targetPath;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public ServiceReference1.DTaskPriority priority;
        
        public EnqueueDownloadRequest()
        {
        }
        
        public EnqueueDownloadRequest(string url, string targetPath, ServiceReference1.DTaskPriority priority)
        {
            this.url = url;
            this.targetPath = targetPath;
            this.priority = priority;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnqueueDownloadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EnqueueDownloadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EnqueueDownloadResult;
        
        public EnqueueDownloadResponse()
        {
        }
        
        public EnqueueDownloadResponse(string EnqueueDownloadResult)
        {
            this.EnqueueDownloadResult = EnqueueDownloadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDownloadQueue", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDownloadQueueRequest
    {
        
        public GetDownloadQueueRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDownloadQueueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDownloadQueueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.DTask[] GetDownloadQueueResult;
        
        public GetDownloadQueueResponse()
        {
        }
        
        public GetDownloadQueueResponse(ServiceReference1.DTask[] GetDownloadQueueResult)
        {
            this.GetDownloadQueueResult = GetDownloadQueueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartDownloadOne", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StartDownloadOneRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.DTask dTask;
        
        public StartDownloadOneRequest()
        {
        }
        
        public StartDownloadOneRequest(ServiceReference1.DTask dTask)
        {
            this.dTask = dTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartDownloadOneResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StartDownloadOneResponse
    {
        
        public StartDownloadOneResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDownloadedList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDownloadedListRequest
    {
        
        public GetDownloadedListRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDownloadedListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDownloadedListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.DTask[] GetDownloadedListResult;
        
        public GetDownloadedListResponse()
        {
        }
        
        public GetDownloadedListResponse(ServiceReference1.DTask[] GetDownloadedListResult)
        {
            this.GetDownloadedListResult = GetDownloadedListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PauseDownload", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PauseDownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string taskId;
        
        public PauseDownloadRequest()
        {
        }
        
        public PauseDownloadRequest(string taskId)
        {
            this.taskId = taskId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PauseDownloadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PauseDownloadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool PauseDownloadResult;
        
        public PauseDownloadResponse()
        {
        }
        
        public PauseDownloadResponse(bool PauseDownloadResult)
        {
            this.PauseDownloadResult = PauseDownloadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResumeDownload", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResumeDownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string taskId;
        
        public ResumeDownloadRequest()
        {
        }
        
        public ResumeDownloadRequest(string taskId)
        {
            this.taskId = taskId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResumeDownloadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResumeDownloadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ResumeDownloadResult;
        
        public ResumeDownloadResponse()
        {
        }
        
        public ResumeDownloadResponse(bool ResumeDownloadResult)
        {
            this.ResumeDownloadResult = ResumeDownloadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelDownload", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelDownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string taskId;
        
        public CancelDownloadRequest()
        {
        }
        
        public CancelDownloadRequest(string taskId)
        {
            this.taskId = taskId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelDownloadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelDownloadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CancelDownloadResult;
        
        public CancelDownloadResponse()
        {
        }
        
        public CancelDownloadResponse(bool CancelDownloadResult)
        {
            this.CancelDownloadResult = CancelDownloadResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.EnqueueDownloadResponse> EnqueueDownloadAsync(ServiceReference1.EnqueueDownloadRequest request)
        {
            return base.Channel.EnqueueDownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetDownloadQueueResponse> GetDownloadQueueAsync(ServiceReference1.GetDownloadQueueRequest request)
        {
            return base.Channel.GetDownloadQueueAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.StartDownloadOneResponse> StartDownloadOneAsync(ServiceReference1.StartDownloadOneRequest request)
        {
            return base.Channel.StartDownloadOneAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetDownloadedListResponse> GetDownloadedListAsync(ServiceReference1.GetDownloadedListRequest request)
        {
            return base.Channel.GetDownloadedListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.PauseDownloadResponse> PauseDownloadAsync(ServiceReference1.PauseDownloadRequest request)
        {
            return base.Channel.PauseDownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResumeDownloadResponse> ResumeDownloadAsync(ServiceReference1.ResumeDownloadRequest request)
        {
            return base.Channel.ResumeDownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CancelDownloadResponse> CancelDownloadAsync(ServiceReference1.CancelDownloadRequest request)
        {
            return base.Channel.CancelDownloadAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WcfServiceLibraryProj/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
